version: '3.7'

services:
  go-app:
    restart: always
    container_name: customer_app
    image: venukishore/customer_app:latest
    build: .
    environment:
      DATABASE_URL: "host=go_db user=postgres password=root dbname=complaints sslmode=disable"
    ports:  
      - "8000:8000"
    depends_on:
      - go_db
  go_db:
    restart: always
    container_name: go_db
    image: postgres:15.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: complaints
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # adminer:
  #   image: adminer:4.8.1
  #   restart: always
  #   depends_on: 
  #     - go_db
  #   ports:
  #     - 8080:8080
volumes:  
  pgdata: {}
